name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-html
          playwright install

      - name: Run Playwright tests with HTML report
        run: |
          mkdir -p reports
          mkdir -p artifacts/screenshots artifacts/videos
          pytest e2e/tests/ \
            --html=reports/ui_report.html \
            --self-contained-html \
            --video on \
            --screenshot on \
            --disable-warnings -v

      - name: Upload UI HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-html-report
          path: reports/ui_report.html

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: artifacts/screenshots

      - name: Upload videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: videos
          path: artifacts/videos

  api-tests:
    runs-on: ubuntu-latest
    needs: ui-tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-html

      - name: Run API tests
        run: |
          mkdir -p reports
          pytest api/tests/ \
            --html=reports/api_report.html \
            --self-contained-html \
            --disable-warnings -v

      - name: Upload API HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-html-report
          path: reports/api_report.html